# Generated by Django 3.0.7 on 2020-07-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ToBeSell',
        ),
        migrations.RemoveField(
            model_name='products',
            name='p_owner',
        ),
    ]
